openapi: 3.0.0
servers:
  - description: Production server
    url: https://vault.apideck.com/integrations
info:
  contact:
    email: hello@apideck.com
    url: /
  description: >
    Welcome to the Vault API ðŸ‘‹


    Building integrations starts with handling user credentials and generating access tokens for the APIs you want to use.


    When you're looking to connect to an API, the first step is authentication.

    Vault helps you store API keys and access tokens from customers.


    The only thing you need to use the Unify APIs is the consumer id, and Vault will do the look-up in the background to perform the API call(s), adding an extra layer of protection to prevent access token leakage.


    ## Why Apideck Vault


    The Vault API allows you to build your own integrations UI, so your customers can activate and configure integrations.


    Through the API, your customers authenticate directly in your app, where Vault will still take care of redirecting to the auth provider and back to your app. This strategy gives you full control over the flow and look & feel of the integration experience.


    Through the Unify dashboard, you can configure which connectors you want to support as integrations, and it also allows you to control which kinds of providers your application supports


    Alternatively, you can use the Hosted Vault, a no-code solution.


    ## Get Started


    To use the Apideck APIs, you need to first sign up for free at [https://app.apideck.com/signup](). Follow the steps below to get started.

    - Create a free account.

    - Sign in to the Apideck Unify Dashboard.

    - Get your API key and the application ID.

    - Select and configure the integrations you want to make available to your users

    - Retrieve the client_id and client_secret for the integration you want to activate (Only needed for OAuth integrations). You can skip this step by using the Apideck sandbox credentials to get you started. (GUIDES per service coming soon)

    - Register the redirect URI for the example app (https://unify.apideck.com/vault/callback) in the list of redirect URIs under your app's settings


    ### Vault API


    If you are building your integration settings UI manually, you can call the Vault API directly.

    The Vault API is for companies who want to completely whitelabel the in-app integrations overview and authentication experience.

    Through the API, your customers authenticate directly in your app where Vault will still take care of redirecting to the auth provider and back to your app.

    This strategy gives you full control over the flow and look & feel of the integration experience.

    Through the Unify dashboard you can configure which connectors you want to support as integrations. and also allows you to control which kinds of providers your application supports.


    If you're already storing access tokens we will help you migrate through our Vault Migration API.


    Beware, this is strategy takes more time to implement and is more complex than the hosted vault strategy.


    ### Hosted Vault


    Hosted Vault is a simple no-code solution, so you don't need to build your own UI to handle the integration settings and authentication. It's a great way to explore Unify without needing to build an integrations overview to get started.


    ![Hosted Vault - Integrations portal](https://app.apideck.com/images/hosted-vault.png)


    Behind the scenes Hosted Vault implements the Vault API endpoints and handles the following features for your customers:


    - Add a connection (for an integration)

    - Handle the OAuth flow

    - Configure connection settings per integration

    - Manage connections

    - Discover and propose integration options


    ## Domain model


    At its core, a domain model creates a web of interconnected entities.


    Our domain model contains five main entity types: Consumer (user, account, team, machine), Application, Connector, Integration, and Connection.


    ## Headers

    Custom headers that are expected as part of the request. Note that [RFC7230](https://tools.ietf.org/html/rfc7230) states header names are case insensitive.


    | Name                  	| Type    	| Required 	| Description                                                                                                                                                    	|

    |-----------------------	|---------	|----------	|----------------------------------------------------------------------------------------------------------------------------------------------------------------	|

    | x-apideck-app-id      	| String  	| Yes      	| The id of your Unify application. Available at https://app.apideck.com/api-keys.                                                                          |

    | x-apideck-consumer-id 	| String  	| Yes      	| The id of the customer stored inside Apideck Vault. This can be a user id, account id, device id or whatever entity that can have integration within your app. 	|

    | x-apideck-raw         	| Boolean 	| No       	| Include raw response. Mostly used for debugging purposes.                                                                                                      	|


    ## Connectors


    A full list of what vendors require which auth flow:


    | Provider               | Provider ID        | Auth Type | Status    |

    | ---------------------- | ------------------ | --------- | --------- |

    | [Copper]()             | copper             | apiKey    | available |

    | [Close]()              | close              | apiKey    | available |

    | [Teamleader]()         | teamleader         | oauth2    | available |

    | [Pipedrive]()          | pipedrive          | oauth2    | available |

    | [Slack]()              | slack              | oauth2    | available |

    | [Google]()             | google             | oauth2    | available |

    | [Google Sheets]()      | google-sheets      | oauth2    | available |

    | [Hubspot]()            | hubspot            | oauth2    | available |

    | [Salesforce]()         | salesforce         | oauth2    | available |

    | [Reply]()              | reply              | apiKey    | available |

    | [MixMax]()             | mixmax             | apiKey    | available |

    | [Intercom]()           | intercom           | oauth2    | available |

    | [Drift]()              | drift              |           | available |

    | [Livechat]()           | livechat           |           | available |

    | [Crisp]()              | crisp              |           | available |

    | [Tink]()               | tink               | oauth2    | available |

    | [Auth0]()              | auth0              | oauth2    | available |

    | [Segment]()            | segment            |           | available |

    | [iubenda]()            | iubenda            |           | available |

    | [Metomic]()            | metomic-io         |           | available |

    | [Google Analytics]()   | google-analytics   |           | available |

    | [Google Tag Manager]() | google-tag-manager |           | available |

    | [Heap]()               | heap               |           | available |

    | [OneTrust]()           | onetrust           |           | available |

    | [journy.io]()          | journy-io          |           | available |

    | [Albacross]()          | albacross          |           | available |


    ## Sandbox (upcoming)


    The sandbox is pre-loaded with data similar to a real-life integrations setup. You can use the preconfigured OAauth configured connectors for testing purposes and can skip this step by using the Apideck sandbox credentials to get you started.


    ## Guides


    - How to configure the OAuth credentials for integration providers (COMING SOON)

    - How to build an integrations UI with Vault (COMING SOON)


    ## FAQ


    __What purpose does Vault serve? Can I just handle the authentication and access token myself?__

    You can store everything yourself, but that defeats the purpose of using Apideck Unify. Handling tokens for multiple providers can quickly become very complex.


    ### Is my data secure?


    Vault employs data minimization, therefore only requesting the minimum amount of scopes needed to perform an API request.


    ### How do I migrate existing data?


    Using our migration API, you can migrate the access tokens and accounts to Apideck Vault. (COMING SOON)


    ### Can I use Vault in combination with existing integrations?


    Yes, you can. The granularity of Unify allows to quickly the use cases you need, while keeping a gradual migration path based on your timeline and requirements.


    ### How does Vault work for Apideck Ecosystem customers?


    Once logged in, pick your ecosystem; on the left-hand side of the screen, you'll have the option to create an application underneath the Unify section.


    ### How to integrate Apideck Vault


    This section covers everything you need to know to authenticate your customers through Vault.

    Vault provides __three strategies__ to use API tokens from your customers:

    - Vault API

    - Hosted Vault

    - Apideck Ecosystem *(COMING SOON)*


    You can also opt to bypass Vault and still take care of authentication flows yourself. Make sure to put the right safeguards in place to protect your customers' tokens and other sensitive data.


    ### What auth types does Vault support?


    What auth strategies does Vault handle? We currently support two flows so your customers can activate an integration.


    #### API keys


    For Services supporting the API key strategy, you will need to provide an in-app form where users can configure their API keys provided by the integration service. You can also use the drop-in solution if you don't want your own integration settings overview.


    #### OAuth 2.0


    ##### Authorization Code Grant Type Flow


    Vault handles the complete Authorization Code Grant Type Flow for you. This flow only supports browser-based (passive) authentication because most identity providers don't allow entering a username and password to be entered into applications that they don't own.


    Certain connectors require an OAuth redirect authentication flow, where the end-user is redirected to the provider's website or mobile app to authenticate.


    This is being handled by the ``/authorize`` endpoint.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Vault API
  version: 0.1.0
  x-logo:
    url: https://developers.apideck.com/icon.png
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/apideck-libraries/openapi-specs/master/vault.yml
      version: "3.0"
  x-providerName: apideck.com
  x-serviceName: vault
security:
  - ApiKeyAuth: []
paths:
  "/authorize/{service_id}/{application_id}":
    get:
      description: >
        __In most cases the authorize link is provided in the
        ``/connections`` endpoint. Normally you don't need to manually generate
        these links.__


        Use this endpoint to authenticate a user with a connector. It will return a 302 redirect to the downstream connector ednpoints.


        Auth links will have a state parameter included to verify the validity of the request. This is the url your users will use to activate OAuth supported integation providers.


        Vault handles the complete Authorization Code Grant Type Flow for you and will redirect you to the dynamic redirect uri you have appended to the url in case this is missing the default redirect uri you have configured for your Unify application.
      operationId: authorize
      parameters:
        - $ref: "#/components/parameters/application_id"
        - $ref: "#/components/parameters/service_id"
        - $ref: "#/components/parameters/state"
        - $ref: "#/components/parameters/redirect_uri"
      responses:
        "200":
          description: ok
      summary: Authorize
      tags:
        - Connections
  /connections:
    get:
      description: >
        This endpoint includes all the configured integrations and contains
        the needed assets

        to build an integrations page where your users can install integrations.

        OAuth2 supported integrations will contain authorize and revoke links to handle the authentication flows.
      operationId: connectionsAll
      parameters:
        - $ref: "#/components/parameters/x-apideck-consumer-id"
        - $ref: "#/components/parameters/x-apideck-app-id"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionList"
          description: ok
      summary: Get all connections
      tags:
        - Connections
    patch:
      description: Used to update settings and API keys (only services that don't
        support OAuth 2.0)
      operationId: connectionsBulkUpdate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BulkUpdateConnections"
        description: Services with their API keys
        required: true
      responses:
        "200":
          description: ok
        "400":
          $ref: "#/components/responses/ValidationException"
        "404":
          $ref: "#/components/responses/NotFound"
      summary: Bulk update connections
      tags:
        - Connections
  "/connections/{unified_api}/{service_id}":
    delete:
      operationId: deleteConnection
      parameters:
        - $ref: "#/components/parameters/service_id"
        - $ref: "#/components/parameters/unified_api"
      responses:
        "204":
          $ref: "#/components/responses/Deleted"
        "400":
          $ref: "#/components/responses/InvalidId"
        "404":
          $ref: "#/components/responses/NotFound"
      summary: Deletes a connection
      tags:
        - Connections
    patch:
      operationId: connectionsUpdate
      parameters:
        - $ref: "#/components/parameters/service_id"
        - $ref: "#/components/parameters/unified_api"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateConnection"
        description: Fields that need to be updated on the resource
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Connection"
          description: ok
        "400":
          $ref: "#/components/responses/InvalidId"
        "404":
          $ref: "#/components/responses/NotFound"
        "405":
          $ref: "#/components/responses/ValidationException"
      summary: Update a connection
      tags:
        - Connections
  "/revoke/{service_id}/{application_id}":
    get:
      description: >
        __In most cases the authorize link is provided in the
        ``/connections`` endpoint. Normally you don't need to manually generate
        these links.__


        Use this endpoint to revoke an existing OAuth connector.


        Auth links will have a state parameter included to verify the validity of the request. This is the url your users will use to activate OAuth supported integation providers.


        Vault handles the complete revoke flow for you and will redirect you to the dynamic redirect uri you have appended to the url in case this is missing the default redirect uri you have configured for your Unify application.
      operationId: revoke
      parameters:
        - $ref: "#/components/parameters/application_id"
        - $ref: "#/components/parameters/service_id"
        - $ref: "#/components/parameters/state"
        - $ref: "#/components/parameters/redirect_uri"
      responses:
        "200":
          description: ok
      summary: Revoke
      tags:
        - Connections
  /sessions:
    post:
      description: >
        Making a POST request to this endpoint will initiate a Hosted Vault
        session. Redirect the consumer to the returned

        url to allow temporary access to manage their integrations and settings.


        Note: This is a short lived token that will expire after 30 minutes (TTL: 1800).
      operationId: createSession
      parameters:
        - $ref: "#/components/parameters/x-apideck-consumer-id"
        - $ref: "#/components/parameters/x-apideck-app-id"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SessionConfig"
        description: Additional redirect uri and/or consumer metadata
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateSession"
          description: ok
      summary: Retrieve a JWT authorization
      tags:
        - Sessions
components:
  parameters:
    application_id:
      description: Application ID of the resource to return
      in: path
      name: application_id
      required: true
      schema:
        type: string
    consumer_id:
      description: ID of the consumer which you want to get or push data from
      in: path
      name: x-apideck-consumer-id
      required: true
      schema:
        type: string
    page:
      description: Page number to start from. Omitting the page parameter will return page 1
      in: query
      name: page
      schema:
        type: integer
    per_page:
      description: Number of records to return per page. Default = 100.
      in: query
      name: per_page
      schema:
        type: integer
    redirect_uri:
      description: URL to redirect back to after authorization. When left empty the
        default configured redirect uri will be used.
      example: https://yoursaasapp.com/integrations
      in: query
      name: redirect_uri
      required: true
      schema:
        type: string
    service_id:
      description: Service ID of the resource to return
      example: pipedrive
      in: path
      name: service_id
      required: true
      schema:
        type: string
    state:
      description: An opaque value the applications adds to the initial request that
        the authorization server includes when redirecting the back to the
        application. This value must be used by the application to prevent CSRF
        attacks.
      in: query
      name: state
      schema:
        type: string
    unified_api:
      description: Unified API
      example: lead
      in: path
      name: unified_api
      required: true
      schema:
        type: string
    x-apideck-app-id:
      description: The ID of your Unify application
      in: header
      name: x-apideck-app-id
      required: true
      schema:
        type: string
    x-apideck-consumer-id:
      description: ID of the consumer which you want to get or push data from
      in: header
      name: x-apideck-consumer-id
      required: true
      schema:
        type: string
  responses:
    Created:
      description: Resource created
    Deleted:
      description: Resource succesfully deleted
    IllegalInput:
      description: Illegal input for operation.
    InvalidId:
      description: Invalid ID supplied.
    InvalidInput:
      description: Invalid input
    NotFound:
      description: Entity not found.
    Updated:
      description: Resource updated
    ValidationException:
      description: Validation exception
  schemas:
    BulkUpdateConnections:
      properties:
        data:
          example:
            api_key: "1223440590540954095"
            enabled: true
            service_id: close
            settings:
              domain_id: apideck.com
              lead_source: webinar
            unified_api: lead
          items:
            $ref: "#/components/schemas/UpdateConnection"
          type: array
      required:
        - data
    Connection:
      allOf:
        - $ref: "#/components/schemas/Service"
        - properties:
            added:
              type: boolean
            addedBy:
              type: string
            addedOn:
              type: string
            authorizationUrl:
              type: string
            authorize:
              type: boolean
            enabled:
              type: boolean
            metadata:
              type: object
            revokeUrl:
              type: string
            status:
              enum:
                - live
                - upcoming
                - requested
              type: string
          type: object
    ConnectionList:
      properties:
        data:
          example:
            - auth_type: oauth2
              authorization_flow_enabled: true
              authorization_url: https://vault.apideck.com/authorize/salesforce/{application_id}
              authorized: true
              authorized_by:
                created_at: 10/11/2019
                external_account_id: spacex
                external_user_id: elonmusk-2219129
                name: Elon Musk
              enabled: true
              form_fields:
                - description: Assign a default lead source to leads
                  disabled: false
                  id: lead_source
                  label: Lead Source
                  mask: true
                  options:
                    - label: Webinar
                      value: webinar
                    - label: Conference
                      value: conference
                  placeholder: Select source
                  required: false
                  type: select
                  validation_message: Invalid lead source
                  validation_rule: ^.{1,}$
                  value: webinar
              icon: https://res.cloudinary.com/apideck/image/upload/v1529456047/catalog/salesforce/icon128x128.png
              id: salesforce
              logo: https://res.cloudinary.com/apideck/image/upload/v1529456047/catalog/salesforce/icon128x128.png
              metadata:
                account_name: test
              name: Salesforce
              revoke_url: https://vault.apideck.com/revoke/salesforce/{application_id}
              status: upcoming
              tag_line: Sync new leads to Salesforce
              unified_api:
                - lead
            - apiKey: "1223440590540954095"
              authType: apiKey
              authorized: true
              enabled: false
              icon: https://res.cloudinary.com/apideck/image/upload/v1529456047/catalog/salesforce/icon128x128.png
              id: close
              logo: https://res.cloudinary.com/apideck/image/upload/v1529456047/catalog/salesforce/icon128x128.png
              metadata:
                account_name: test
              name: close
              status: live
              tag_line: Sync new leads to close
              unified_api:
                - lead
          items:
            $ref: "#/components/schemas/Connection"
          type: array
      required:
        - data
      title: Connection List
    CreateSession:
      example:
        session_uri: http://vault.apideck.com/session/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3RfdXNlcl9pZCIsImFwcGxpY2F0aW9uX2lkIj
      properties:
        session_uri:
          type: string
      title: Create Session
      type: object
    Error:
      properties:
        code:
          example: ERR-01234
          type: string
        href:
          example: http://example.org/docs/errors/#ERR-01234
          type: string
        message:
          example: Session has expired at unix time 1385243766. The current unix time is
            1385848532.
          type: string
        title:
          example: OAuthException
          type: string
    GeneralError:
      items:
        $ref: "#/components/schemas/Error"
      type: array
    Service:
      properties:
        auth_type:
          enum:
            - oauth2
            - apiKey
          type: string
        icon:
          type: string
        id:
          type: string
        logo:
          type: string
        name:
          type: string
        tagLine:
          type: string
        unified_api:
          items:
            enum:
              - lead
              - crm
              - accounting
              - spreadsheet
              - email
              - script
          type: array
      type: object
    SessionConfig:
      example:
        consumer_metadata:
          account_name: SpaceX
          image: https://imgix.com/honeybadger
          user_name: Elon Musk
        redirect_uri: https://mysaas.com/dashboard
        theme:
          favicon: https://www.intercom.com/_next/static/images/favicon-348ad8df6c167d93fb894e8bcb4dcd2a.png
          logo: https://res.cloudinary.com/apideck/image/upload/v1554113418/catalog/intercom/logo.png
          primary_color: "#286efa"
          privacy_url: https://compliance.apideck.com/privacy-policy
          sidepanel_background_color: "#286efa"
          sidepanel_text_color: "#FFFFFF"
          terms_url: https://www.termsfeed.com/terms-conditions/957c85c1b089ae9e3219c83eff65377e
          vault_name: Intercom
      properties:
        consumer_metadata:
          properties:
            account_name:
              type: string
            image:
              type: string
            user_name:
              type: string
          type: object
        redirect_uri:
          type: string
        theme:
          properties:
            favicon:
              type: string
            primary_color:
              type: string
            privacy_url:
              type: string
            sidepanel_background_color:
              type: string
            sidepanel_text_color:
              type: string
            terms_url:
              type: string
            vault_name:
              type: string
          type: object
      title: Session config
      type: object
    UpdateConnection:
      properties:
        api_key:
          anyOf:
            - type: string
            - nullable: true
        enabled:
          type: boolean
        metadata:
          type: object
        settings:
          type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-Key
      type: apiKey
